### PR TITLE
[xdg-utils] Update to 1.1.3. JB#55586

### PR DESCRIPTION
**Pull request by pvuorela**
@mlehtima @Tomin1

### CODE REVIEW

**Comment by Thaodan** [comment]
Did you update those pregenerated files e.g. manpages?

**Review by okodron — COMMENTED** [review]
`%make_build` can be used.
`rm -rf %{buildroot}` is not necessary now.

**Comment by xfade** [comment]
Mirror: https://github.com/sailfishos-mirror/xdg-utils

**Comment by pvuorela** [comment]
Updated mirror, adjusted spec and recreated the temporary files. Next time I'll just remove the -doc package :/

**Review by mlehtima — APPROVED** [review]

**Pull request merged**
